### ISSUE TITLE
Argument order in constructor

### ISSUE THREAD

**Issue by RobinBobin** [tidepool-org/cp2102#1]
Hello!

The README states that product id precedes vendor id, but the source code for the cp2102 class states the order is the opposite.

Maybe you could find some time to correct the corresponding README line.

Thanks.

**Comment by RobinBobin** [comment]
I mean the order of the arguments in the constructor of the cp2102 class.

**Comment by gniezen** [comment]
Thanks @RobinBobin , I've updated the README.
